### ISSUE TITLE
Trying to load dev version of build into app

### ISSUE THREAD

**Issue by starsinmypockets** [datopian/datapackage-views-js#17]
## description
I'm trying to load a dev version of datapackage-views into the frontend... basically I am:
* $ yarn build
* `$ cp -r build path/to/frontend-v2/public/datapackage-view`
* add  `<script src="/static/datapackage-views/build/static/js/main.54875131.chunk.js"></script>` to `views/showcase.html`

Not sure what I'm missing here.. it does load the script but does not run (ie, never processes the array of htmlElements that react-dom is looking for

I see we using githack.com to load the deployment script... maybe there is an extra step I am missing?

**Comment by starsinmypockets** [comment]
I got this working, I needed to include the entire script from the compiled index.html I'll paste an example below

**Comment by anuveyatsu** [comment]
@starsinmypockets yes, exactly. `main.xxx.chunk.js` won't work without other generated JS modules. What I'm doing right now is I have a npm script called `build:non-optimized` which generates single JS module (which is huge!) so that it has the static name `main.js` so can be imported in frontend-v2 app without change.

However, we want to utilize code splitting/optimizing feature that CRA provides so let's do the following:

1. Build
2. Rename and move the chunks into `/dist/` directory with static names, e.g., remove the hashes: `main.chunk.js`, `runtime~main.js` and `2.chunk.js`
3. Same for stylesheets

**Comment by anuveyatsu** [comment]
@starsinmypockets next step would be using https://facebook.github.io/create-react-app/docs/code-splitting

**Comment by starsinmypockets** [comment]
Sounds good, I'm doing essentially the same thing, but removing the hashes makes things simpler and I can script this easily.

**Comment by anuveyatsu** [comment]
Do you think we can close this? @starsinmypockets

**Comment by starsinmypockets** [comment]
Closed: Will not fix
